# Generated by Django 4.2.3 on 2023-09-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_trainingprogram_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_typeid',
            new_name='company_id',
        ),
    ]
